services:
  server:
    build: ./srcs
    ports:
      - '42069:25565'
    container_name: mc_server
    restart: no
    volumes:
      - type: bind
        source: ./volume/server
        target: /mcserver
    environment:
      MOTD: "CHICKEN JOCKEEEEEY"
      MAX_PLAYERS: 64
      LEVEL_NAME:
      SEED:
      SERVER_IP:
      SIM_DISTANCE:
      VIEW_DISTANCE: 16
      ALLOCATED_RAM: "16G"
      SERVER_JAR_URL: "https://fill-data.papermc.io/v1/objects/74e3a26c32a09dcbb213aec27a107467739e27b12dbe82b1a3e7a4b7d059c730/paper-1.21.10-129.jar"
    stdin_open: true
    tty: true
